import type { Metadata } from "next";
import { Geist, Geist_Mono, Lobster, Jost } from "next/font/google";
import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const lobsterFont = Lobster({
  weight: "400",
  subsets: ["latin"],
});

const jostFont = Jost({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const font = {
  lobsterFont,
  jostFont,
}



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jostFont.className} ${lobsterFont.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
